name: Build

# Sets permissions of the GITHUB_TOKEN to allow pushing a conatainer image to ghcr.io
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      repo:
        description: Git repository URL to clone
        required: true
        type: string
      branch:
        description: Branch or ref to checkout
        required: true
        type: string
      workspace:
        description: Workspace folder under workspaces/
        required: true
        type: string
      imageName:
        description: Name of the image to build
        required: true
        type: string
      imageTag:
        description: Tag of the image to build
        required: false
        type: string
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      branch:
        required: true
        type: string
      workspace:
        required: true
        type: string
      imageName:
        required: true
        type: string
      imageTag:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'christoph-jerolimov'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Clone repository
        env:
          REPO: ${{ inputs.repo }}
          BRANCH: ${{ inputs.branch }}
        run: |
          git init source
          cd source
          git remote add origin "$REPO"
          git fetch --depth 1 origin "$BRANCH"
          git checkout FETCH_HEAD

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: source/workspaces/${{ inputs.workspace }}
        run: yarn install

      - name: Package plugins
        working-directory: source/workspaces/${{ inputs.workspace }}
        env:
          IMAGE: ${{ inputs.imageName }}:${{ inputs.imageTag || 'latest' }}
        run: npx -y @red-hat-developer-hub/cli@1.10.x plugin package --tag "$IMAGE"

      - name: Install podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Push to GitHub Container Registry
        env:
          IMAGE: ${{ inputs.imageName }}:${{ inputs.imageTag || 'latest' }}
        run: |
          echo ${{ github.token }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin
          podman push "$IMAGE" ghcr.io/${{ github.repository_owner }}/$IMAGE
