name: redhat-developer/rhdh-plugins cron

# Sets permissions of the GITHUB_TOKEN to allow pushing a container image to ghcr.io
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

on:
  # schedule:
  #   - cron: '0 4 * * 1'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        workspace:
          - adoption-insights
          - ai-integrations
          - app-defaults
          - boost
          - bulk-import
          - extensions
          - global-header
          - homepage
          - intelligent-assistant
          - orchestrator
          - quickstart
          - scorecard
          - theme
          - translations
    uses: ./.github/workflows/build.yaml
    with:
      repo: https://github.com/redhat-developer/rhdh-plugins
      branch: main
      workdir: workspaces/${{ matrix.workspace }}
      imageName: rhdh-${{ matrix.workspace }}
