name: redhat-developer/rhdh-plugins cron

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        workspace:
          - adoption-insights
          - ai-integrations
          - app-defaults
          - bulk-import
          - extensions
          - global-header
          - homepage
          - lightspeed
          - quickstart
          - scorecard
          - theme
          - translations
    uses: ./.github/workflows/build.yaml
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
    with:
      repo: https://github.com/redhat-developer/rhdh-plugins
      branch: main
      workdir: workspaces/${{ matrix.workspace }}
      imageName: rhdh-${{ matrix.workspace }}
